You work in XYZ Company as a Python Data Scientist. The company officials
have collected some data on salaries based on year of experience and wish for
you to create a model from it.
Dataset: data.csv
Tasks To Be Performed:Load the dataset using pandas
2. Extract data from years experience column is a variable named X
3. Extract data from the salary column is a variable named Y
4. Divide the dataset into two parts for training and testing in 66% and 33%
proportion
5. Create and train Linear Regression Model on training set
6. Make predictions based on the testing set using the trained model
7. Check the performance by calculating the r2 score of the model

In [5]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

# Step 1: Load the data from the CSV file
data = pd.read_csv('data.csv')
data

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [6]:

# Step 2: Extract data from the 'years experience' column
X = data['YearsExperience'].values.reshape(-1, 1)

In [8]:
# Step 3: Extract data from the 'salary' column
Y = data['Salary'].values

In [10]:

# Step 4: Split the dataset into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.33, random_state=42)

In [11]:
# Step 5: Create and train the Linear Regression Model
model = LinearRegression()
model.fit(X_train, Y_train)

LinearRegression()

In [12]:

# Step 6: Make predictions on the testing set
Y_pred = model.predict(X_test)

In [13]:
# Step 7: Calculate the r2 score of the model
r2_score = r2_score(Y_test, Y_pred)

# Print the r2 score
print("R2 Score:", r2_score)

R2 Score: 0.9553063138044949